title: Data Visualization
description: "This site presents visualizations for analyzing license data in the stae of Illinois"
baseurl: "/"
url: "https://your-github-username.github.io/your-repository-name" # Update with your actual URL
theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge
